title: Vems OlShop
description: "Replikasi profil Instagram dan katalog produk modular dengan Jekyll"
author: ""
url: ""
baseurl: "/toko"
avatar: 

collections:
  products:
    output: true
    permalink: /products/:name/

permalink: pretty
markdown: kramdown

